### ISSUE TITLE
systemd --user session

### ISSUE THREAD

**Issue by soredake** [aroig/dotfiles#1]
>My session is currently broken, since all systemd --user runs outside any session.

No updates on this issue?

**Comment by aroig** [comment]
Not really, I think. I still use the user instance to launch most of my applications, including graphical ones, and they run outside the session. In the long term, I think the notion of session will change, and those user services will probably be fine.

In the mean time, I avoided any software that broke outside of the user session. The only annoying thing was that usb stick auto-mounting via gvfs did not work outside the session. But I find things quite usable anyway. In fact, I prefer the flexibility of running apps in services, and being able to declare dependencies between them, socket activation, timers, etc, even when this means I need to mount external devices with `sudo mount`.
